---
title: "Tick Density Forecasting Project"
output: html_document
author: E.M. Beasley, S.L. Ladeau, & M.C. Dietze
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Data and code for forecasting tick densities across sampling locations of the National Ecological Observatory Network (NEON) and Cary Institute for Ecosystem Studies (hereafter, Cary). For a full list of files and metadata, see the metadata file (coming soon). 

## Associated Publications

Coming Soon

## Data Preparation

All scripts required for data processing can be found in the DataProcessing folder. These scripts read from and save to the Data folder.

All NEON data can be downloaded using the script [neon_download.R](neon_download.R). DayMet meteorological data can be downloaded using the script [intakeDayMet.R](intakeDayMet.R). The most up-to-date Cary data must be obtained from one of [their repositories](https://www.caryinstitute.org/science/data).  

### Tick Drags

### Small Mammal Trapping

### Weather

## Model Workflow

Coming Soon