---
title: "Exploratory analysis of Amblyomma parameters (Φ, θ, β)"
author: "Neo Chatterjee"
date: "2026-04-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Plots and model summaries for each parameter-covariate combination
```{r, echo = FALSE}
library(dplyr)
library(lubridate)
library(broom)

#obtain parameter .csv's
files <- list.files("/usr4/ugrad/neochatt/TickForecast/Data", pattern = "Amblyomma", full.names = TRUE)

#parameter names
pars <- c("phi.l.mu", "phi.n.mu", "phi.a.mu", "theta.ln", "theta.na", "beta[1]", "beta[2]", "beta[3]", "beta[4]", "beta[5]", "beta[6]", "beta[7]", "beta[8]", "beta[9]", "beta[10]", "beta[11]", "beta[12]", "beta[13]", "beta[14]")

stats_ndvi <- data.frame(
 parameter = character(length(pars)),
 R_squared = numeric(length(pars)),
 p = numeric(length(pars)),
 significant = logical(length(pars))
)

stats_lai <- data.frame(
 parameter = character(length(pars)),
 R_squared = numeric(length(pars)),
 p = numeric(length(pars)),
 significant = logical(length(pars))
)

r = 1

for(par in pars){
  
  deer_files <- list()
  
  #load vegetation data
  lai <- read.csv("/usr4/ugrad/neochatt/TickForecast/Data/all_LAIs.csv")
  ndvi <- read.csv("/usr4/ugrad/neochatt/TickForecast/Data/all_VIs.csv")

  #render it plottable
  lai$date <- as.Date(lai$date, format = "%m/%d/%Y")
  ndvi$date <- as.Date(ndvi$date)
  
  for (f in files) {
    dat <- read.csv(f)
    dat <- dat |> filter(node == par)
    dat$start.date <- as.Date(dat$start.date)
    deer_files[[length(deer_files) + 1]] <- dat
  }

  deer_files <- bind_rows(deer_files)

  deer_files <- deer_files |>
    mutate(week = floor_date(start.date, "week")) |>
    group_by(week, siteID) |>
    mutate(par = mean(mean, na.rm = TRUE))
  
  params <- deer_files |>
    group_by(siteID) |>
    summarize(par = mean[which.max(as.Date(start.date))])
  
  lai <- lai |>
    group_by(siteID) |>
    summarize(lai = mean(lai_mean, na.rm = TRUE))
  
  ndvi <- ndvi |>
    group_by(siteID) |>
    summarize(ndvi = mean(ndvi_mean, na.rm = TRUE))
  
  kat <- params |>
    inner_join(lai, by = "siteID") |>
    inner_join(ndvi, by = "siteID")
  
  
  #===============NDVI===========
  plot(kat$ndvi, kat$par, pch = 16, cex = 0.7, xlab = "NDVI", ylab = par, main   = paste0("Deer ", par, " vs NDVI"))
  abline(lm(kat$par ~ kat$ndvi), col = "red")
  print(summary(lm(kat$par ~ kat$ndvi)))
  
  
  R_squared <- summary(lm(kat$par ~ kat$ndvi))$adj.r.squared
  pVal <- tidy(lm(kat$par ~ kat$ndvi))$p.value[2]
  
  stats_ndvi$parameter[r] <- par
  stats_ndvi$R_squared[r] <- R_squared
  stats_ndvi$p[r] <- pVal
  stats_ndvi$significant[r] <- pVal < 0.1
  
  
  
  
  #===============LAI===========
  plot(kat$lai, kat$par, pch = 16, cex = 0.7, xlab = "LAI", ylab = par, main     = paste0("Deer ", par, " vs LAI"))
  abline(lm(kat$par ~ kat$lai), col = "red")
  print(summary(lm(kat$par ~ kat$lai)))
  
  
  
  R_squared <- summary(lm(kat$par ~ kat$lai))$adj.r.squared
  pVal <- tidy(lm(kat$par ~ kat$lai))$p.value[2]
  
  stats_lai$parameter[r] <- par
  stats_lai$R_squared[r] <- R_squared
  stats_lai$p[r] <- pVal
  stats_lai$significant[r] <- pVal < 0.1
  
  r <- r+1
}









```

Model statistics; first table is NDVI, second is LAI (significance defined as p < 0.10)
```{r, echo = FALSE}

stats_ndvi
stats_lai



```
