---
title: "CDF_analysis"
author: "Neo Chatterjee"
date: "2026-06-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, echo = FALSE}
library(dplyr)
library(lubridate)

LAG <- data.frame()

sites <- c("GREN", "HNRY", "TEA", "BLAN", "SCBI", "SERC", "ORNL", "MLBS", "TREE", "HARV")

for(site in sites){
  
  ticks <- read.csv("/usr4/ugrad/neochatt/TickForecast/Data/tickLong.csv") |>
  mutate(
    collectDate = as.Date(collectDate),
    year = year(collectDate)
  ) |>
  filter(scientificName == "Ixodes scapularis")

  lai <- read.csv("/usr4/ugrad/neochatt/TickForecast/Data/MODIS_site_LAIs.csv") |>
  mutate(date = as.Date(date),
         year = year(date))

  lai <- lai |>
    filter(siteID == site)

    lai <- lai[lai$year != 2015, ]
lai$DOY <- as.numeric(format(lai$date, "%j"))


  deer <- ticks |>
    filter(siteID == site) |>
    filter(scientificName == "Ixodes scapularis") |>
    filter(lifeStage == "Nymph") |>
    arrange(collectDate) |>
    group_by(collectDate) |>
    summarise(count = sum(processedCount)) 
  deer$year <- year(deer$collectDate)
  deer$DOY <- as.numeric(format(deer$collectDate, "%j"))


  lai <- lai[lai$year != 2015, ]
  deer <- deer[deer$year > 2015, ]
  deer <- na.omit(deer)
  
  
  years <- min(deer$year):2023
  
  par(mfrow = c(2, 4))
  
  lags <- data.frame(
    siteID = vector(mode = "character", length = length(years)),
    year = years,
    lag = vector(mode = "numeric", length = length(years))
  )
  lags$siteID <- site
  
  i <- 1
  
  
  pheno <- read.csv("/usr4/ugrad/neochatt/TickForecast/Data/phenology_DOYs.csv")
  pheno <- pheno |>
    filter(siteID == site)
  
  
  for(y in years){
    
    leaf <- lai |>
      filter(year == y)
    
    tick <- deer |>
      filter(year == y)
    
    temp <- pheno |>
      filter(year == y)
    
    leaf <- leaf[1:(nrow(leaf) / 2), ]
    
    leaf <- leaf |> 
      arrange(date) |>
      mutate(lai_increase = pmax(lai_median - lag(lai_median), 0))
    
    leaf$lai_increase[1] <- 0
    
    
    deer <- deer |>
      filter(month(collectDate) <= 7)
    
    
    library(MASS)
    
    
    # LAI: generate DOY observations weighted by LAI increase
    lai_doy <- rep(leaf$DOY, times = round(leaf$lai_increase * 100))
    lai_fit <- fitdistr(lai_doy, "normal")
    # lai_fit$estimate gives you mean and sd
    
    # Ticks: generate DOY observations weighted by count
    tick_doy <- rep(tick$DOY, times = tick$count)
    tick_fit <- fitdistr(tick_doy, "normal")
    
    # The lag
    
    c1 <- qnorm(0.50, mean = tick_fit$estimate["mean"], sd = tick_fit$estimate["sd"]) 
    
    c2 <- qnorm(0.50, mean = lai_fit$estimate["mean"], sd = lai_fit$estimate["sd"])
  
    #lag <- c1 - temp$greenup_doy
    lag <- c1 - c2
    
    
    curve(pnorm(x, mean = lai_fit$estimate["mean"], sd = lai_fit$estimate["sd"]), 
          from = 1, to = 250, col = "green", xlab = "DOY", ylab = "CDF")
    curve(pnorm(x, mean = tick_fit$estimate["mean"], sd = tick_fit$estimate["sd"]), 
          add = TRUE, col = "black")
    abline(v = temp$greenup_doy, col = "red", lty = 2)
    
  
    
    
    lags$lag[i] <- lag
    i <- i + 1
    
  }
  
  lags$lag_week <- lags$lag/7
  lags$lag_month <- lags$lag/30
    
   
  LAG <- rbind(LAG, lags)
}


LAG <- na.omit(LAG)





i <- 1

for(s in sites){
  temp <- LAG |>
    filter(siteID == s)
  
  if(i == 1){
    plot(temp$year, temp$lag, pch = 16, cex = 0.7, col = cols[i], ylim = c(min(LAG$lag), max(LAG$lag)), xlab = "Year", ylab = "Lag (days)")
    lines(temp$year, temp$lag, col = cols[i])
  } else {
    points(temp$year, temp$lag, pch = 16, cex = 0.7, col = cols[i])
    lines(temp$year, temp$lag, col = cols[i])
  }
  
  i <- i +1
  
}


legend("topright", 
       legend = sites, 
       col    = cols, 
       lty    = 1, 
       lwd    = 2)




```








