---
title: "Land_cover_analysis (NLCD, fragstats)"
author: "Neo Chatterjee"
date: "2026-05-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



### GROSS COUNTS
```{r, echo = FALSE}

nlcd <- read.csv("/projectnb/dietzelab/ebeasley/TickForecast/Data/full_NLCD.csv")
frag <- read.csv("/projectnb/dietzelab/ebeasley/TickForecast/Data/fragstats.csv")


nlcd$Shannon <- 0

for(r in 1:nrow(nlcd)){
  for(c in 2:ncol(nlcd)){
    p <- nlcd[r, c]
    
    if(!is.na(p) && p > 0){
      nlcd$Shannon[r] <- nlcd$Shannon[r] - (p * log(p))
    }
  }
}


plot(nlcd$Shannon, frag$mean_nymph_count, xlab = "Shannon diversity", ylab = "Mean nymph count", main = "Mean nymph count vs Shannon diversity", pch = 16, cex = 0.7)
abline(lm(frag$mean_nymph_count ~ nlcd$Shannon), col = "red")
print(summary(lm(frag$mean_nymph_count ~ nlcd$Shannon)))

plot(nlcd$Shannon, frag$mean_adult_count, xlab = "Shannon diversity", ylab = "Mean adult count", main = "Mean adult count vs Shannon diversity", pch = 16, cex = 0.7)
abline(lm(frag$mean_adult_count ~ nlcd$Shannon), col = "red")
print(summary(lm(frag$mean_adult_count ~ nlcd$Shannon)))



plot(frag$pct_dominant, frag$mean_nymph_count, xlab = "%-dominant land cover", ylab = "Mean nymph count", main = "Mean nymph count vs %-dominant", pch = 16, cex = 0.7)
abline(lm(frag$mean_nymph_count ~ frag$pct_dominant), col = "red")
print(summary(lm(frag$mean_nymph_count ~ frag$pct_dominant)))


plot(frag$pct_dominant, frag$mean_adult_count, xlab = "%-dominant land cover", ylab = "Mean adult count", main = "Mean adult count vs %-dominant", pch = 16, cex = 0.7)
abline(lm(frag$mean_adult_count ~ frag$pct_dominant), col = "red")
print(summary(lm(frag$mean_adult_count ~ frag$pct_dominant)))


plot(frag$edge_m_per_ha, frag$mean_nymph_count, xlab = "Edge (m/ha)", ylab = "Mean nymph count", main = "Mean nymph count vs edge", pch = 16, cex = 0.7)
abline(lm(frag$mean_nymph_count ~ frag$edge_m_per_ha), col = "red")
print(summary(lm(frag$mean_nymph_count ~ frag$edge_m_per_ha)))


plot(frag$edge_m_per_ha, frag$mean_adult_count, xlab = "Edge m/ha", ylab = "Mean adult count", main = "Mean adult count vs edge", pch = 16, cex = 0.7)
abline(lm(frag$mean_adult_count ~ frag$edge_m_per_ha), col = "red")
print(summary(lm(frag$mean_adult_count ~ frag$edge_m_per_ha)))


```



###PARAMETERS
```{r, echo = FALSE}
library(ggplot2)


library(dplyr)
library(lubridate)
library(broom)

#obtain parameter .csv's
files <- list.files("/usr4/ugrad/neochatt/TickForecast/Data", pattern = "Ixodes", full.names = TRUE)

#parameter names
pars <- c("phi.l.mu", "phi.n.mu", "phi.a.mu", "theta.ln", "theta.na", "beta[1]", "beta[2]", "beta[3]", "beta[4]", "beta[5]", "beta[6]", "beta[7]", "beta[8]", "beta[9]", "beta[10]", "beta[11]", "beta[12]", "beta[13]", "beta[14]")

for(par in pars){
  
  deer_files <- list()

  
  for (f in files) {
    dat <- read.csv(f)
    dat <- dat |> filter(node == par)
    dat$start.date <- as.Date(dat$start.date)
    deer_files[[length(deer_files) + 1]] <- dat
  }

  deer_files <- bind_rows(deer_files)

  deer_files <- deer_files |>
    mutate(week = floor_date(start.date, "week")) |>
    group_by(week, siteID) |>
    mutate(par = mean(mean, na.rm = TRUE))
  
  params <- deer_files |>
    group_by(siteID) |>
    summarize(param_value = mean[which.max(as.Date(start.date))])
  
  
  frag_plot <- frag |>
    left_join(params, by = c("site" = "siteID"))
  
  
  
  p <- ggplot(frag_plot, aes(x = factor(lc_dominant), y = param_value)) +
    geom_boxplot() +
    labs(
      title = par,
      x = "Dominant land cover",
      y = "Parameter value"
    )

  
  
  frag_plot |>
    count(lc_dominant, is.na(param_value))
  
  print(p)
  
  
  
}



```




